CREATE TABLE IF NOT EXISTS  PRICES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT NOT NULL,
    START_DATE DATETIME NOT NULL,
    END_DATE DATETIME NOT NULL,
    PRICE_LIST INT NOT NULL,
    PRODUCT_ID INT NOT NULL,
    PRIORITY INT NOT NULL,
    PRICE DECIMAL(10, 2) NOT NULL,
    CURRENCY VARCHAR(3) NOT NULL,
    VERSION BIGINT
);

--  índice combinado para las columnas START_DATE, END_DATE, PRODUCT_ID y BRAND_ID
CREATE INDEX idx_prices_dates_product_brand ON PRICES (START_DATE, END_DATE, PRODUCT_ID, BRAND_ID);